function Round10(){
let t1=parseInt(breath.value*1000);
let t2=parseInt(breath_holding_on.value*1000);
let t3=parseInt(exhalation.value*1000);
let t4=parseInt(breath_holding_off.value*1000);

delay(0)
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})
.then(block1)
.then(function(){return delay(t1);})
.then(block2)
.then(function(){return delay(t2);})
.then(block3)
.then(function(){return delay(t3);})
.then(block4)
.then(function(){return delay(t4);})

}
